name: permits_pipeline_env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py37hc8dfbb8_1001
  - attrs=19.3.0=py_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - bleach=3.1.5=pyh9f0ad1d_0
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py37hc8dfbb8_0
  - click=7.1.2=pyh9f0ad1d_0
  - dbus=1.13.6=h2f22bb5_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37hc8dfbb8_1001
  - expat=2.2.9=h4a8c4bd_2
  - geographiclib=1.50=py_0
  - geopy=1.22.0=pyh9f0ad1d_0
  - gettext=0.19.8.1=h46ab8bc_1002
  - glib=2.65.0=h577aef8_0
  - icu=64.2=h6de7cb9_1
  - importlib-metadata=1.6.1=py37hc8dfbb8_0
  - importlib_metadata=1.6.1=0
  - ipykernel=5.3.0=py37h43977f1_0
  - ipython=7.15.0=py37hc8dfbb8_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.1=py37hc8dfbb8_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=h0b31af3_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_1
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - krb5=1.17.1=h14dd6a4_1
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libclang=9.0.1=default_hf57f61e_0
  - libcxx=10.0.0=h1af66ff_2
  - libedit=3.1.20191231=hed1e85f_0
  - libffi=3.2.1=h4a8c4bd_1007
  - libgfortran=4.0.0=2
  - libiconv=1.15=h0b31af3_1006
  - liblapack=3.8.0=16_openblas
  - libllvm9=9.0.1=h7475705_1
  - libopenblas=0.3.9=h3d69b6c_0
  - libpng=1.6.37=hbbe82c9_1
  - libpq=12.2=h489d428_1
  - libsodium=1.0.17=h01d97ff_0
  - llvm-openmp=10.0.0=h28b9765_0
  - markupsafe=1.1.1=py37h9bfed18_1
  - mistune=0.8.4=py37h9bfed18_1001
  - nbconvert=5.6.1=py37hc8dfbb8_1
  - nbformat=5.0.6=py_0
  - ncurses=6.1=h0a44026_1002
  - notebook=6.0.3=py37hc8dfbb8_0
  - nspr=4.20=h0a44026_1000
  - nss=3.47=hc0980d9_0
  - numpy=1.18.5=py37h7687784_0
  - openssl=1.1.1g=h0b31af3_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.5=py37h94625e5_0
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=pyh9f0ad1d_0
  - pcre=8.44=h4a8c4bd_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pip=20.1.1=py_1
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.5=py_1
  - prompt_toolkit=3.0.5=1
  - psycopg2=2.8.5=py37he655712_1
  - ptyprocess=0.6.0=py_1001
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py37ha62fc16_3
  - pyrsistent=0.16.0=py37h9bfed18_0
  - python=3.7.6=cpython_h1fd5dd1_6
  - python-dateutil=2.8.1=py_0
  - python-dotenv=0.13.0=pyh9f0ad1d_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - pyzmq=19.0.1=py37haec44b1_0
  - qt=5.12.5=h514805e_3
  - qtconsole=4.7.5=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - readline=8.0=hcfe32e1_0
  - send2trash=1.5.0=py_0
  - setuptools=47.3.1=py37hc8dfbb8_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.30.1=h93121df_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbbe82c9_0
  - tornado=6.0.4=py37h9bfed18_1
  - traitlets=4.3.3=py37hc8dfbb8_1
  - wcwidth=0.2.5=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py37_0
  - xz=5.2.5=h0b31af3_0
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h0b31af3_1006
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1

